# Generated by Django 2.0.13 on 2020-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='cor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='area',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
