# Generated by Django 2.0.13 on 2020-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
