# Generated by Django 2.0.13 on 2020-01-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_area_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(on_delete=False, related_name='area', to='portal.Area'),
        ),
    ]
