# Generated by Django 2.0.13 on 2020-01-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200117_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(on_delete=True, related_name='area', to='portal.Area'),
        ),
    ]
