# Generated by Django 2.0.13 on 2020-01-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(on_delete='', related_name='area', to='portal.Area'),
        ),
    ]
