# Generated by Django 2.0.13 on 2020-01-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200117_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='portal.Area'),
        ),
    ]
