# Generated by Django 2.0.13 on 2020-01-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200118_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
