# Generated by Django 2.0.13 on 2020-01-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_noticia_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
